name: Build and Deploy Spring Boot WAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
 
    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew
 
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build/libs/
      
    - name: List target directory contents
      run: ls -l target

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: ldbar-war

      - name: List target directory contents
        run: ls -l ./

      - name: Rename WAR file
        run: mv ldbar-1.0.1.war demo.war

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Upload WAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: sshtesting
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "ldbar.war"
          target: ${{ secrets.SERVER_IP }}

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Wait for Service to Start
        run: sleep 3

      - name: Test GET all values
        run: curl -f --location 'https://${{ secrets.SERVER_IP }}:8443/ldbar/api/v1' --insecure

      - name: Test GET specific value
        run: curl -f --location 'https://${{ secrets.SERVER_IP }}:8443/ldbar/api/v1/1' --insecure

      - name: Test POST values
        run: |
          curl -f --location --request POST "https://${{ secrets.SERVER_IP }}:8443/ldbar/api/v1" \
          --data 'Chile' \
          --insecure \
          --header 'Content-Type: text/plain'
      
      - name: Test PUT values
        run: |
          curl -f --location --request PUT 'https://${{ secrets.SERVER_IP }}:8443/ldbar/api/v1/6' \
          --header 'Content-Type: text/plain' \
          --data 'Marruecos' \
          --insecure

      - name: Test DELETE values
        run: curl -f --location --request DELETE 'https://${{ secrets.SERVER_IP }}:8443/ldbar/api/v1/6' --insecure
